### ISSUE TITLE
Why did you remove the ability to send a command to the server?

### ISSUE THREAD

**Issue by Leopere** [alfonsojon/minecraft-init#4]
This was a great little function to have in case you wanted to schedule things other than just `service minecraft say "message"`

**Comment by alfonsojon** [comment]
I intended on updating this script to play nicer with system.d, and a lot of the "screen" hackery was pretty buggy on many systems with system.d. I intend on reimplementing this feature; I'm sorry for the inconvenience!

**Comment by Leopere** [comment]
Not a problem and it apparently still functions fine its just not documented with `service minecraft help`
